# vich_uploader:
#     db_driver: orm

#     mappings:
#         property_images:
#             uri_prefix:         /images/properties
#             upload_destination: '%kernel.project_dir%/public/images/properties

# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        property_images:
            uri_prefix:         /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'